name: Auto Bundle & Release

on:
  push:
    branches:
      - main

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run bundler
        run: python bundler.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Auto Release ${{ github.run_number }}
          files: |
            bundled.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
